// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.15.1_@libsql+client@0.14.0_@parcel+watcher@2.5.0_@types+node@22.10.5_better-sqlite3@11_lc4uqkzr4at65wjovkbmjdfuvi/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/content/:collection/database.sql': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.0.0-alpha.8_@libsql+client@0.14.0_magicast@0.3.5_pg@8.13.1_rollup@4.30.0/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/api/content/:collection/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.0.0-alpha.8_@libsql+client@0.14.0_magicast@0.3.5_pg@8.13.1_rollup@4.30.0/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}